# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-24 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161122_1629'),
    ]
