# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_user'),
        ('blog', '0005_auto_20161124_1138'),
    ]

    operations = [
    ]
