# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_merge_20161124_1528'),
    ]

    operations = [

        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
