# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-24 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20161124_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),

    ]
