# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161124_1718'),
        ('blog', '0008_auto_20161125_1018'),
    ]

    operations = [
    ]
