# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161125_1135'),
    ]

    operations = [

    ]
