# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_user'),
    ]

    operations = [


        migrations.RemoveField(
            model_name='category_post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category_post',
            name='post',
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category_post',
        ),
    ]
