# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user'),
        ('blog', '0011_auto_20161125_1123'),
    ]

    operations = [
    ]
