# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_date',
        ),
    ]
