# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_category_created_date'),
    ]

    operations = [
    
    ]
