# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20161125_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
