# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20161125_1928'),
        ('blog', '0015_user'),
    ]

    operations = [
    ]
