# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_user'),
    


    ]
