# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_user'),
    ]

    operations = [
    
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to='blog.Like'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='New blog post', max_length=100),
        ),
    ]
