# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-26 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_user'),
    ]

        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='summary text', max_length=50),
            preserve_default=False,
        ),
    ]
