# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-26 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20161126_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=100),
        ),
    ]
